package modules.views;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

public class Game extends javax.swing.JFrame {
    private static Game instanceGame;
    private String[][] board;
    private JButton[][] buttons;
    private int rows;
    private int cols;
    
    private Game(String[][] board) {
        this.board = board;
        this.rows = board.length;
        this.cols = board[0].length;
        createGame();
        setLocationRelativeTo(null);
        setVisible(true);
    }
        
    public static Game getInstanceGame (String[][] board) {
        if (instanceGame == null) {
            instanceGame = new Game(board);
        }
        
        return instanceGame;
    }
    
    private void createGame () {
        JPanel tablero = new JPanel();
        tablero.setLayout(new GridLayout(this.rows, this.cols));
        buttons = new JButton[rows][cols];
        
        for (int i = 0; i < this.rows; i++) {
            for (int j = 0; j < this.cols; j++) {
                buttons[i][j] = new JButton(board[i][j]);
                buttons[i][j].setPreferredSize(new Dimension(40, 40));
                
                buttons[i][j].setOpaque(false);
                buttons[i][j].setContentAreaFilled(false);
                buttons[i][j].setBorderPainted(false);
                
                int coordX = i;
                int coordY = j;
                
                buttons[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        revealCell(coordX, coordY);
                    }
                });
                
                tablero.add(buttons[i][j]);
            }
        }
        
        JPanel panelContainer = new JPanel(new BorderLayout());
        panelContainer.setBorder(new EmptyBorder(20, 20, 20, 20)); // Margin de 20
        panelContainer.add(tablero, BorderLayout.CENTER);
        
        getContentPane().removeAll(); // Limpiar cualquier contenido previo
        add(panelContainer, BorderLayout.CENTER);
        pack(); // Ajustar tamaño ventana
        revalidate(); // Refrescar la interfaz gráfica
        repaint();
    }
    
    private void revealCell(int coordX, int coordY) {
        System.out.println("Destapar celda " + coordX + ", " + coordY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
