package modules.views;
import java.awt.Color;
import javax.swing.JPanel;
import modules.views.utils.ImageLoader;
public class LoseScreen extends javax.swing.JFrame {
    private static LoseScreen instance;
    
    public LoseScreen() {
        setUndecorated(true); // Quitar decoraciones estándar
        initComponents();
        setLocationRelativeTo(null);
        setSize(600, 600);
        setTransparentBackground();
        LabelGameOver.setIcon(ImageLoader.setImageLabel("/resources/over.png", 400, 400));
        LabelGameOver.repaint();
    }
    
    private void setTransparentBackground () {
        JPanel contentPane = (JPanel) this.getContentPane();
        contentPane.setOpaque(false);
        this.setBackground(new Color(0, 0, 0, 0));
    }
    
    public static LoseScreen getInstanceGameOverScreen () {
        if (instance == null) {
            instance = new LoseScreen();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRestartGame = new javax.swing.JButton();
        LabelGameOver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRestartGame.setBackground(new java.awt.Color(153, 51, 255));
        BtnRestartGame.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        BtnRestartGame.setForeground(new java.awt.Color(255, 153, 51));
        BtnRestartGame.setText("Restart Game");
        BtnRestartGame.setBorder(null);
        BtnRestartGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRestartGame.setFocusable(false);
        BtnRestartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestartGameActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRestartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 160, 50));
        getContentPane().add(LabelGameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRestartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestartGameActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Index.getInstanceIndex().setVisible(true);
    }//GEN-LAST:event_BtnRestartGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRestartGame;
    private javax.swing.JLabel LabelGameOver;
    // End of variables declaration//GEN-END:variables

}

